# Generated by Django 4.0.1 on 2022-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_placas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='imagem',
            field=models.ImageField(default=None, upload_to='placas/'),
        ),
    ]
