# Generated by Django 4.0.1 on 2022-01-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_placas', '0002_alter_placa_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='imagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
