# Generated by Django 4.0.1 on 2022-01-26 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_quis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dificuldade',
            new_name='Categoria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='id_dificuldade',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_quis.categoria'),
        ),
    ]
