# Generated by Django 4.0.1 on 2022-01-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quis', '0003_alternativa_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativa',
            name='id_categoria',
        ),
    ]
