# Generated by Django 4.0.1 on 2022-01-30 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_quis', '0004_remove_alternativa_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='código',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='enunciado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_quis.categoria'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
