# Generated by Django 4.0.1 on 2022-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quis', '0005_alter_alternativa_conteudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(default=None, upload_to='', verbose_name='imagem'),
        ),
    ]
