# Generated by Django 4.0.1 on 2022-01-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quis', '0006_pergunta_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(default=None, upload_to='perguntas/'),
        ),
    ]
